from . import bim
from . import bim_categ
from . import bim_udn
from . import bim_purchase_order
from . import bim_sale_order
from . import bim_departaments
from . import bim_partner_type
from . import bim_documentation
from . import bim_hr
